# Generated by Django 5.2 on 2025-04-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('color', models.CharField(default='primary', help_text='Nombre de la clase CSS para el color (ej: primary, success, danger)', max_length=20, verbose_name='color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
            ],
            options={
                'verbose_name': 'prioridad de proyecto',
                'verbose_name_plural': 'prioridades de proyecto',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_final', models.BooleanField(default=False, help_text='Indica si es un estado que finaliza el proyecto', verbose_name='es estado final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
            ],
            options={
                'verbose_name': 'estado de proyecto',
                'verbose_name_plural': 'estados de proyecto',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectpriority', verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectstatus', verbose_name='estado'),
        ),
    ]
