services:
  web:
    build: .
    env_file:
      - .env
    container_name: django_gunicorn
    # Enlaza el contenedor a la red de Docker para que Nginx pueda acceder a él
    networks:
      - django-network
    volumes:
      - "/mnt/d/Documentos/Desarrollo/Django:/app"
  nginx:
    image: nginx:1.21
    container_name: nginx_proxy
    ports:
      - "80:80"  # Mapea el puerto 80 del host al 80 del contenedor Nginx
    networks:
      - django-network
    volumes:
      # Monta la configuración de Nginx y los archivos estáticos
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - "/mnt/d/Documentos/Desarrollo/Django/static:/app/static"
    depends_on:
      - web

networks:
  django-network:
    driver: bridge