# Generated by Django 4.2.14 on 2024-08-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='importe',
            field=models.FloatField(),
        ),
    ]
