# Generated by Django 5.1.4 on 2025-01-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_transaccion_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio neto', 'Patrimonio Neto'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=20),
        ),
    ]
