# Generated by Django 5.1.4 on 2025-01-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_alter_cuenta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
