# Generated by Django 5.1.4 on 2025-01-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_transaccion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
