# Generated by Django 5.1.4 on 2025-01-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_transaccion_importe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tickets/')),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
