# Generated by Django 5.1.4 on 2025-02-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_ticketimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='tipo',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio neto', 'Patrimonio Neto'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], default='gasto', max_length=20),
        ),
    ]
