# Generated by Django 5.2 on 2025-10-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_presupuesto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketimagen',
            name='imagen',
            field=models.FileField(upload_to='tickets/'),
        ),
    ]
